# Constant variables
SCREEN_WIDTH=1280
SCREEN_HEIGHT=720
SPRITE_SCALING_PLAYER=0.35
FULLSCREEN = False

BORDERS_OFFSET = 15

MOVEMENT_SPEED = 5
SECURITAS_SPEED = 5
SPRITE_SCALING_BEER=0.100
SPRITE_SCALING_SECURITAS=0.35
BEER_CONVERGENCE=30

RIGHT=1
LEFT=2
UP=3
DOWN=4

HIGHSCORE_FILE="highscore"

# MENU VARIABLES

LINE_BREAK= 50

PLAY_POSITION_X=SCREEN_WIDTH / 2
PLAY_POSITION_Y=(2/3)*SCREEN_HEIGHT
PLAY_HEIGHT=54
PLAY_WIDTH=int(4*0.4*PLAY_HEIGHT) #Nb_lettre*largeur_lettre

MENU_HIGHSCORE_POSITION_X=SCREEN_WIDTH / 2
MENU_HIGHSCORE_POSITION_Y=(2/3)*SCREEN_HEIGHT - PLAY_HEIGHT - LINE_BREAK
MENU_HIGHSCORE_HEIGHT=54
MENU_HIGHSCORE_WIDTH=int(10*0.4*MENU_HIGHSCORE_HEIGHT)

QUIT_POSITION_X=SCREEN_WIDTH / 2
QUIT_POSITION_Y=(2/3)*SCREEN_HEIGHT - PLAY_HEIGHT - MENU_HIGHSCORE_HEIGHT - 2*LINE_BREAK
QUIT_HEIGHT=54
QUIT_WIDTH=int(4*0.4*QUIT_HEIGHT)

GAME_OVER_POSITION_X=SCREEN_WIDTH / 2
GAME_OVER_HEIGHT=54
GAME_OVER_POSITION_Y=(SCREEN_HEIGHT / 2) + GAME_OVER_HEIGHT


RESTART_POSITION_X=SCREEN_WIDTH / 2
RESTART_POSITION_Y=(SCREEN_HEIGHT / 2) - GAME_OVER_HEIGHT
RESTART_HEIGHT=24

HIGHSCORE_POSITION_X=SCREEN_WIDTH / 2
HIGHSCORE_POSITION_Y=SCREEN_HEIGHT - LINE_BREAK
HIGHSCORE_HEIGHT=54
HIGHSCORE_WIDTH=int(10*0.4*HIGHSCORE_HEIGHT)