""" Scale of each object """ 
SPRITE_SCALING_WALL= 0.1
SPRITE_SCALING_SECU= 0.05 
SPRITE_SCALING_PLAYER= 0.15
SPRITE_SCALING_BIER=0.1

BIER_COUNT=50
SECU_COUNT=8

#must be a double
TOTAL_TIME=10.0

SCREEN_WIDTH=800
SCREEN_HEIGHT=600
OFFSCREEN_SPACE=0
LEFT_LIMIT = -OFFSCREEN_SPACE
RIGHT_LIMIT = SCREEN_WIDTH + OFFSCREEN_SPACE
BOTTOM_LIMIT = -OFFSCREEN_SPACE
TOP_LIMIT = SCREEN_HEIGHT + OFFSCREEN_SPACE

MOVEMENT_SPEED=3
